### ISSUE TITLE
Consider implementing the neuroelectronics SDK to record data directly in Bonsai

### ISSUE THREAD

**Issue by bruno-f-cruz** [emotional-cities/pluma-experiments#11]
https://www.neuroelectrics.com/solution/software-integrations/sdk
Otherwise, it would be nice to find a way to automatically start acquisition from Bonsai. The SDK also seems to include some sort of CLI toolkit that might enable such a feature.

**Comment by aspaNeuro** [comment]
Experiments are using NIC2 software independently, bonsai is sending at random times LSL messages to sync devices.
