### ISSUE TITLE
Validate Empatica connection at the start of the workflow

### ISSUE THREAD

**Issue by bruno-f-cruz** [emotional-cities/pluma-experiments#12]
We have successfully implemented and tested #10.

However, it would be nice to validate that the server correctly started and that a connection was achieved. This could be don't by implementing some sort of handshake logic:

1 - Launch the `Emmpatica Server` and wait for it to start (10 seconds should be safe)
2. - Once it starts, send a  `device_discover_list` command and print the output to console to list all devices. If no message is received without a timeout period, crash the workflow since this will likely mean the a connection was not successfully established.
3 - Once successfully established, send the remaining stream-enabling messages 

Some additional notes:

- Externalize the empatica device name (currently hardcoded)

**Comment by aspaNeuro** [comment]
Currently we have a monitor that checks the connection and datastreams for all devices.
we still need to:

- [x] Externalize the empatica device name (currently hardcoded)

**Comment by aspaNeuro** [comment]
Empatica device Id is now external f0ee0102bba40f4a693e4926033dc101ab7b39d9
