### ISSUE TITLE
Run hardware stress tests

### ISSUE THREAD

**Issue by glopesdev** [emotional-cities/pluma-experiments#39]
Run the system for long periods of time, e.g. more than 4 hours to mimic the duration of one day of data collection.

**Comment by aspaNeuro** [comment]
With the current data collections being made, the system is proven to be stable during the different data collections, 1/2h pause and collect again, the batteries of the pupil labs does not last 4h acquiring data without pausing to recharge, so the full 4h collecting data stress test cannot be achieved.
