### ISSUE TITLE
Ensure all omnicept Glia streams are pushing data on startup

### ISSUE THREAD

**Issue by glopesdev** [emotional-cities/pluma-experiments#53]
We have observed on occasion that omnicept Glia streams fail to trigger the callbacks in Unity Omnicept SDK. So far we have seen this only at startup, specifically for the IMU and heartrate streams. If confirmed that this is only a startup issue, we probably can detect it by raising an exception if no data is sent for a specified period of time.

**Comment by aspaNeuro** [comment]
Fixed in 10994a2acdc32af2199aa374aabb5c94443f02a7 with ControlPanelVR.bonsai.
The experimenter has a red flag on all streams failing to show data.
