### ISSUE TITLE
Record VR videos from Unity

### ISSUE THREAD

**Issue by pedro-msrocha** [emotional-cities/pluma-experiments#54]
Add the possibility of recording videos from the trajectories that we do in VR Alfama space.

**Comment by aspaNeuro** [comment]
## Requirements from FMUL
Record Videos from Unity as a simple video recorder app.

1. Create spawn points to start recording on configurable specific locations.
2. There is no acquisition of bio signals while the videos are being recorded 
3. The videos created will be then used in the same style as previous experiment 2

From IGOT need to check:
1. In the normal run the current VR setup and details is enough for the experiment requirements
5. in the optimized scenario we need to check with IGOT all the requirements in terms of visual layout.
